# Build image
# `docker-compose -f docker-compose.yml build`
# Push to registry
# `docker-compose -f docker-compose.yml push`

version: '3.7'
services:

  app:
    image: registry.lts.harvard.edu/lts/docker-nodejs-template:0.0.1
    build:
      context: ./
      dockerfile: Dockerfile
    command: npm start